# Generated by Django 4.2.3 on 2023-07-17 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_player_season_team_created_at_team_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField()),
                ('home_goals', models.IntegerField()),
                ('away_goals', models.IntegerField()),
                ('home_shots', models.IntegerField()),
                ('away_shots', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='TeamSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('ties', models.IntegerField()),
                ('players', models.ManyToManyField(to='league.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to='league.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to='league.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shots', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playergame_game_requests_created', to='league.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playergame_player_requests_created', to='league.player')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('PP', 'Power Play'), ('SH', 'Short handed'), ('EN', 'Empty Net')], max_length=2)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_game_requests_created', to='league.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_player_requests_created', to='league.player')),
                ('primary_assist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_primary_assist_requests_created', to='league.player')),
                ('secondary_assist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_assist_requests_created', to='league.player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='team_away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_away_requests_created', to='league.teamseason'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_home_requests_created', to='league.teamseason'),
        ),
    ]
