# Generated by Django 4.2.3 on 2023-08-29 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_game_alter_player_email_alter_team_name_teamseason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamseason',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamseason_team_requests_created', to='league.team'),
        ),
    ]
