# Generated by Django 4.2.3 on 2023-08-29 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('league', '0004_alter_teamseason_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_player_requests_created', to='users.player'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='primary_assist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_primary_assist_requests_created', to='users.player'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='secondary_assist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_assist_requests_created', to='users.player'),
        ),
        migrations.AlterField(
            model_name='playergame',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playergame_player_requests_created', to='users.player'),
        ),
        migrations.AlterField(
            model_name='teamseason',
            name='players',
            field=models.ManyToManyField(to='users.player'),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
