# Generated by Django 4.2.3 on 2023-09-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('league', '0005_alter_goal_player_alter_goal_primary_assist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamseason',
            name='players',
            field=models.ManyToManyField(blank=True, to='users.player'),
        ),
    ]
