# Generated by Django 4.2.3 on 2023-09-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_alter_teamseason_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_date',
            field=models.DateTimeField(),
        ),
    ]
